rey/Bfh.Wba.AspNetCore/Bfh.Wba.AspNetCore.Web/Controllers/AccountingController.cs
using System;
using System.Collections.Generic;
using Bfh.Wba.AspNetCore.Web.FakeData;
using Bfh.Wba.AspNetCore.Web.Models;
using Bfh.Wba.AspNetCore.Web.ViewModels;
using Microsoft.AspNetCore.Mvc;


namespace Bfh.Wba.AspNetCore.Web.Controllers
{
	public class AccountingController : Controller
    {
	    public IActionResult Index()
        {
            return View();
        }

		[Route("{controller}/{action}/{type}")]
		public IActionResult Group(AccountGroupCategory type, string selectedGroupId)
		{
			return type switch
			{
				AccountGroupCategory.SachgruppenBilanz => Tree("Sachgruppen Bilanz", FakeAccountingData.SachgruppenBilanz, selectedGroupId),
				AccountGroupCategory.SachgruppenEr => Tree("Sachgruppen Erfolgsrechnung", FakeAccountingData.SachgruppenER, selectedGroupId),
				AccountGroupCategory.SachgruppenIr => Tree("Sachgruppen Investitionsrechnung", FakeAccountingData.SachgruppenIR, selectedGroupId),
				AccountGroupCategory.Funktionen => Tree("Funktionen", FakeAccountingData.Funktionen, selectedGroupId),
				_ => RedirectToAction("Index")
			};
		}

		[Route("{controller}/{action}/{topicType}")]
		public IActionResult Selection(AccountGroupCategory topicType, string functionId, string topicId)
		{
			string typeKey;
			string title;
			KontoGruppenListe topicGroupList;
			Dictionary<string, Konto> accounts;
			Konto account;
			switch (topicType)
			{
				case AccountGroupCategory.SachgruppenEr:
					typeKey = "ER";
					title = "Erfolgsrechnung";
					topicGroupList = FakeAccountingData.SachgruppenER;
					accounts = FakeAccountingData.ER;
					break;
				case AccountGroupCategory.SachgruppenIr:
					typeKey = "IR";
					title = "Investitionsrechnung";
					topicGroupList = FakeAccountingData.SachgruppenIR;
					accounts = FakeAccountingData.IR;
					break;
				default:
					typeKey = "";
					title = "";
					topicGroupList = new KontoGruppenListe();
					accounts = new Dictionary<string, Konto>();
					break;
			}

			ViewData["Type"] = typeKey;

			return View("ER_IR", new ER_IR_ViewModel
			{
				Title = title,
				Funktionen = FakeAccountingData.Funktionen,
				Sachgruppen = topicGroupList,
				Konten = accounts,
				Konto = new Konto
				{
					Funktion = FakeAccountingData.Funktionen.Find(functionId), 
					Sachgruppe = topicGroupList.Find(topicId)
				}
			});
		}

		public IActionResult Create(string funktion, string sachgruppe, string type)
        {
            ViewData["Type"] = type;

            return View(new Konto 
            {
                Nummer = 0,
                Name = "",
                Funktion = FakeAccountingData.Funktionen.Find(funktion),
                Sachgruppe = ((type == "ER") ? FakeAccountingData.SachgruppenER : FakeAccountingData.SachgruppenIR).Find(sachgruppe)
            });
        }

        [HttpPost]
        public IActionResult Create(Konto konto, string funktion, string sachgruppe, string type)
        {
            ViewData["Type"] = type;

            konto.Funktion = FakeAccountingData.Funktionen.Find(funktion);
            konto.Sachgruppe = ((type == "ER") ? FakeAccountingData.SachgruppenER : FakeAccountingData.SachgruppenIR).Find(sachgruppe);

            if (ModelState.IsValid)
            {
                try
                {
                    var list = ((type == "ER") ? FakeAccountingData.ER : FakeAccountingData.IR);
                    list.Add(konto.Kontonummer, konto);

                    return RedirectToAction(type);
                }
                catch (Exception ex)
                {
                    ModelState.AddModelError(String.Empty, ex.Message);
                }
            }

            return View(konto);
        }

        protected IActionResult Tree(string title, KontoGruppenListe list, string id)
        {
            ViewData["Id"] = id;
            ViewData["Title"] = title;
            return View("Tree", list);
        }
    }
}

rey/Bfh.Wba.AspNetCore/Bfh.Wba.AspNetCore.Web/Controllers/DepartmentController.cs
using Bfh.Wba.AspNetCore.Web.FakeData;
using Bfh.Wba.AspNetCore.Web.ViewModels;
using Microsoft.AspNetCore.Mvc;

namespace Bfh.Wba.AspNetCore.Web.Controllers
{
	public class DepartmentController : Controller
	{
		public IActionResult Index()
		{
			var data = DepartmentData.Departments;
			var vm = new DepartmentIndexViewModel()
			{
				Departments = DepartmentData.Departments,
				PreselectedDepartmentId = DepartmentData.Departments[2].Id
			};
			return View(vm);
		}
	}
}

rey/Bfh.Wba.AspNetCore/Bfh.Wba.AspNetCore.Web/Views/Shared/_Layout.cshtml
@using Bfh.Wba.AspNetCore.Web.ViewModels
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Unicorns are real!</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">Unicorns are real!</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex flex-sm-row-reverse">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item dropdown">
							<a class="nav-link dropdown-toggle text-dark" data-toggle="dropdown" asp-area="" asp-controller="" asp-action="" role="button" aria-haspopup="true" aria-expanded="false">Home</a>
	                        <div class="dropdown-menu">
		                        <a class="dropdown-item" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
		                        <a class="dropdown-item" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
	                        </div>
                        </li>
	                    <li class="nav-item">
							<a class="nav-link text-dark" asp-area="" asp-controller="Department" asp-action="Index">Departments</a>
	                    </li>
	                    <li class="nav-item dropdown">
		                    <a class="nav-link dropdown-toggle text-dark" data-toggle="dropdown" asp-area="" asp-controller="" asp-action="" role="button" aria-haspopup="true" aria-expanded="false">Accounting</a>
		                    <div class="dropdown-menu">
			                    <a class="dropdown-item" asp-area="" asp-controller="Accounting" asp-action="Group" asp-route-type="@AccountGroupCategory.Funktionen">Kontogruppen Funktion</a>
			                    <a class="dropdown-item" asp-area="" asp-controller="Accounting" asp-action="Group" asp-route-type="@AccountGroupCategory.SachgruppenBilanz">Sachgruppe Bilanz</a>
			                    <a class="dropdown-item" asp-area="" asp-controller="Accounting" asp-action="Group" asp-route-type="@AccountGroupCategory.SachgruppenEr">Sachgruppe Erfolgsrechnung</a>
			                    <a class="dropdown-item" asp-area="" asp-controller="Accounting" asp-action="Group" asp-route-type="@AccountGroupCategory.SachgruppenIr">Sachgruppe Investitionsrechnung</a>
			                    <div class="dropdown-divider"></div>
			                    <a class="dropdown-item" asp-area="" asp-controller="Accounting" asp-action="Selection" asp-route-topicType="@AccountGroupCategory.SachgruppenBilanz">Bilanz</a>
			                    <a class="dropdown-item" asp-area="" asp-controller="Accounting" asp-action="Selection" asp-route-topicType="@AccountGroupCategory.SachgruppenEr">Erfolgsrechnung</a>
			                    <a class="dropdown-item" asp-area="" asp-controller="Accounting" asp-action="Selection" asp-route-topicType="@AccountGroupCategory.SachgruppenIr">Investitionsrechnung</a>
		                    </div>
	                    </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container-fluid">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2019 - Bfh.Wba.AspNetCore.Web - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @RenderSection("Scripts", required: false)
</body>
</html>