pfahrer/bti7272-wba2web-19-20/04 Models/ModelsExamples/Controllers/KontoController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using ModelsExamples.Models;

namespace ModelsExamples.Controllers
{
    public class KontoController : Controller
    {
        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Funktionen(string id)
        {
            return Tree("Funktionen", 
                Data.Funktionen, id);
        }

        public IActionResult SGBilanz(string id)
        {
            return Tree("Sachgruppen Bilanz", 
                Data.SachgruppenBilanz, id);
        }

        public IActionResult SGER(string id)
        {
            return Tree("Sachgruppen Erfolgsrechnung", 
                Data.SachgruppenER, id);
        }

        public IActionResult SGIR(string id)
        {
            return Tree("Sachgruppen Investitionsrechnung", 
                Data.SachgruppenIR, id);
        }

        public IActionResult ER(string funktion, string sachgruppe)
        {
            ViewData["Type"] = "ER";

            return View("ER_IR", new ER_IR_ViewModel
            {
                Title = "Erfolgsrechnung",
                Funktionen = Data.Funktionen,
                Sachgruppen = Data.SachgruppenER,
                Konten = Data.ER,
                Konto = new Konto
                {
                    Funktion = Data.Funktionen.Find(funktion), 
                    Sachgruppe = Data.SachgruppenER.Find(sachgruppe)
                }
            });
        }

        public IActionResult IR(string funktion, string sachgruppe)
        {
            ViewData["Type"] = "IR";

            return View("ER_IR", new ER_IR_ViewModel
            {
                Title = "Investitionsrechnung",
                Funktionen = Data.Funktionen,
                Sachgruppen = Data.SachgruppenIR,
                Konten = Data.IR,
                Konto = new Konto
                {
                    Funktion = Data.Funktionen.Find(funktion),
                    Sachgruppe = Data.SachgruppenIR.Find(sachgruppe)
                }
            });
        }

        public IActionResult Create(string funktion, string sachgruppe, string type)
        {
            ViewData["Type"] = type;

            return View(new Konto 
            {
                Nummer = 0,
                Name = "",
                Funktion = Data.Funktionen.Find(funktion),
                Sachgruppe = ((type == "ER") ? Data.SachgruppenER : Data.SachgruppenIR).Find(sachgruppe)
            });
        }

        [HttpPost]
        public IActionResult Create(Konto konto, string funktion, string sachgruppe, string type)
        {
            ViewData["Type"] = type;

            konto.Funktion = Data.Funktionen.Find(funktion);
            konto.Sachgruppe = ((type == "ER") ? Data.SachgruppenER : Data.SachgruppenIR).Find(sachgruppe);

            if (ModelState.IsValid)
            {
                try
                {
                    var list = ((type == "ER") ? Data.ER : Data.IR);
                    list.Add(konto.Kontonummer, konto);

                    return RedirectToAction(type);
                }
                catch (Exception ex)
                {
                    ModelState.AddModelError(String.Empty, ex.Message);
                }
            }

            return View(konto);
        }

        protected IActionResult Tree(string title, KontoGruppenListe list, string id)
        {
            ViewData["Id"] = id;
            ViewData["Title"] = title;
            return View("Tree", list);
        }
    }
}

pfahrer/bti7272-wba2web-19-20/04 Models/ModelsExamples/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - ModelsExamples</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">HRM2</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex flex-sm-row-reverse">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Konto" asp-action="Funktionen">Funktionen</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Konto" asp-action="SGBilanz">SG Bilanz</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Konto" asp-action="ER">Erfolgsrechnung</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Konto" asp-action="IR">Investitionsrechnung</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2019 - ModelsExamples - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @RenderSection("Scripts", required: false)
</body>
</html>